### ISSUE TITLE
Why is the blog template not included?

### ISSUE THREAD

**Issue by bolonio** [histaff/website-static#1]
Why is the blog template not included? I would love to have the blog as well!!! Please add it :) Thanks!

**Comment by mostafasoufi** [comment]
The blog handled by WordPress and if you would like, I can create another repo for them.

**Comment by bolonio** [comment]
I would love to. I really like the theme, but I was missing the blog part. My idea is to have the blog with markdown inside Gatsby, so it would be really cool if you can create the repo to see it :) Thanks!!

**Comment by mostafasoufi** [comment]
Done :)
https://github.com/histaff/website-blog

**Comment by bolonio** [comment]
Thanks :)
